### ISSUE TITLE
Performance difference between repo's models and torchvision models

### ISSUE THREAD

**Issue by zankner** [yaodongyu/TRADES#24]
Hey, thanks for this repo. I came across this and I wanted to see if it was an issue. There seems to be a significant change in run time when switching from one of the models implemented in your repo and the official torchvision models.

Running `train_trades_cifar10.py` and specifying the model as `model = ResNet18()` from the TRADES repo, the time per batch is ~ 0.8 seconds.

Running `train_trades_cifar10.py` and specifying the model as `model = torchvision.models.resnet18()`, the time per batch is ~ 0.28 seconds.

I checked to make sure that it wasn't due to model size, and the models have 11181642 trainable params each.

Any advice on why the behavior is this way would be greatly appreciated.

**Comment by hongyanz** [comment]
Hi @zankner 

Thanks very much for raising the question. Did you observe a 0.8/0.28 ~= 2.86x speedup by torchvision.models.resnet18(), not necessarily for each batch, but for the whole training process? We also recommend using the official resnet18 call by PyTorch.

Regarding potential reasons for the observed speed difference, we conjecture that it is because of Lines 81, 86 and 87, where we use F.xxx (the left code is by torchvision and the right code is by our resent 18). Also, the "flatten" operation is typically faster than the "view" operation. But the functioning of the two models should be the same (as you have tested, they have the same number of trainable parameters).

![8761619318224_ pic_hd](https://user-images.githubusercontent.com/28879075/115978613-2bf2e600-a5b3-11eb-8a89-3d5e8ef7bce4.jpg)

**Comment by zankner** [comment]
Thanks for the response, the times that I reported were per batch, and while I haven't timed a whole epoch I would assume it would be the same.

I haven't been able to train both models to completion yet, but looking at their results for the first epoch there seems to be a bit of a discrepancy. Using the repos `ResNet18` the pgd val acc. is .24, while using the torchvision `resnet18` the pgd val acc. is .196.

**Comment by zankner** [comment]
Actually, after running it a few more times, on average they seem to have about the same score.

**Comment by hongyanz** [comment]
We believe that it is the randomness that causes the .24 vs. .196 val acc. Running multiple times, as you have observed, give about the same score. If you do not care about time, using either model to test TRADES should give the same number. Anyway, thanks again for pointing out the time difference.
