### ISSUE TITLE
Random Initialization in Attack

### ISSUE THREAD

**Issue by hendrycks** [yaodongyu/TRADES#4]
For comparability with other evaluations in the literature, it might be useful to first add random noise to the image then begin PGD.
https://github.com/yaodongyu/TRADES/blob/master/pgd_attack_cifar10.py#L51
In a quick-and-dirty experiment, adding attack random initialization decreased TRADES model adversarial accuracy by ~1%.

Recently, it has also [become apparent](https://github.com/evaluating-adversarial-robustness/adv-eval-paper/issues/19) that multiple random restarts in evaluation is important, so adding that functionality might be useful as well.

**Comment by hongyanz** [comment]
Thanks for proposing this. Sure, we are happy to do it.

We think the ~1% reduction in adversarial accuracies is because the random noise itself degrades the classifier performance a little bit, as in the training procedure we do not apply Gaussian data augmentation. However, we think ~1% reduction in adversarial accuracies is not a big issue. Anyway, thanks for sharing your discovery with us.

**Comment by hendrycks** [comment]
> Gaussian data augmentation

By random initialization, I am having in mind perturbations from the uniform distribution. https://github.com/MadryLab/cifar10_challenge/blob/master/pgd_attack.py#L47

**Comment by hongyanz** [comment]
I see. Thanks for informing us. Perhaps uniform (distribution) data augmentation during the training procedure might alleviate the ~1% reduction in accuracy. Sure, we will add the new functionality during evaluation in the later update soon.

**Comment by hongyanz** [comment]
We have added new functionality of random initialization in our updated codes:
https://github.com/yaodongyu/TRADES/blob/master/pgd_attack_cifar10.py#L26
https://github.com/yaodongyu/TRADES/blob/master/pgd_attack_mnist.py#L26
